
name: Check Bandit scanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install flit pytest

            - name: Install Bandit
              run: |
                  python -m pip install bandit

            - name: Run Bandit
              run: |
                  python -m bandit --exit-zero -f json -r -o tests/scans/bandit/latest.json tests/payload/
                  python -m flit build
                  python -m pip install dist/vulnerabilities-*.whl
                  python -m pytest tests/test_bandit_parser.py
